// <auto-generated />
using System;
using Capacitaciones.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Capacitaciones.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260701163333_AdminUserUsuarioRed")]
    partial class AdminUserUsuarioRed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Capacitaciones.Domain.Entities.AdminUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Nombres")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UltimoLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("UsuarioRed")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioRed")
                        .IsUnique()
                        .HasDatabaseName("UX_AdminUser_UsuarioRed");

                    b.ToTable("AdminUser", "dbo");
                });

            modelBuilder.Entity("Capacitaciones.Domain.Entities.Area", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("UX_Area_Nombre");

                    b.ToTable("Area", "dbo");
                });

            modelBuilder.Entity("Capacitaciones.Domain.Entities.Asistente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<Guid>("AreaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("Calificacion")
                        .HasColumnType("decimal(4,2)");

                    b.Property<Guid>("CapacitacionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EmailUsuario")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("EstadoAsistencia")
                        .HasColumnType("int");

                    b.Property<int?>("EstadoEnvioCertificado")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaEnvioCertificado")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInscripcion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaMarcacionAsistencia")
                        .HasColumnType("datetime2");

                    b.Property<string>("Firma")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Identificacion")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("MensajeErrorEnvio")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("CapacitacionId", "FechaInscripcion")
                        .HasDatabaseName("IX_Asistente_Capacitacion_Fecha");

                    b.HasIndex("CapacitacionId", "Identificacion")
                        .IsUnique()
                        .HasDatabaseName("UX_Asistente_Capacitacion_Identificacion");

                    b.ToTable("Asistente", "dbo");
                });

            modelBuilder.Entity("Capacitaciones.Domain.Entities.Capacitacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Capacitador")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("CargoCapacitador")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DuracionMinutos")
                        .HasColumnType("int");

                    b.Property<string>("EmailCapacitador")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<bool>("EmiteCertificado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("EmpresaCapacitador")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime>("FechaHoraInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirmaCapacitador")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogoContentType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LogoPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("ModalidadId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("PuntajeMinimo")
                        .HasColumnType("decimal(4,2)");

                    b.Property<string>("Tema")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("TipoActividadId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TipoCertificacion")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("UX_Capacitacion_Codigo");

                    b.HasIndex("ModalidadId");

                    b.HasIndex("TipoActividadId");

                    b.ToTable("Capacitacion", "dbo");
                });

            modelBuilder.Entity("Capacitaciones.Domain.Entities.CapacitacionResponsable", b =>
                {
                    b.Property<Guid>("CapacitacionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ResponsableId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.HasKey("CapacitacionId", "ResponsableId");

                    b.HasIndex("ResponsableId");

                    b.HasIndex("CapacitacionId", "Orden")
                        .IsUnique()
                        .HasDatabaseName("UX_CapacitacionResponsable_Capacitacion_Orden");

                    b.ToTable("CapacitacionResponsable", "dbo");
                });

            modelBuilder.Entity("Capacitaciones.Domain.Entities.Colaborador", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("JobPosition")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("MaritalStatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Province")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Sex")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Society")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("WorkArea")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Cedula")
                        .IsUnique()
                        .HasDatabaseName("UX_Colaborador_Cedula");

                    b.ToTable("Colaborador", "dbo");
                });

            modelBuilder.Entity("Capacitaciones.Domain.Entities.ConfiguracionNumeracion", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("SiguienteNumero")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UltimaActualizacion")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ConfiguracionNumeracion", "dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            SiguienteNumero = 1
                        });
                });

            modelBuilder.Entity("Capacitaciones.Domain.Entities.Convenio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("AreaColaborador")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("AutorizadoPor")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CargoColaborador")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("CedulaColaborador")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CentroCostos")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("ConvenioFirmado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid?>("ConvenioReferenciaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("EmpresaColaborador")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaCorte")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime?>("FechaFinCurso")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaFirma")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaIngreso")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaInicioCurso")
                        .HasColumnType("datetime2");

                    b.Property<string>("GeneroColaborador")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<decimal?>("Horas")
                        .HasColumnType("decimal(6,2)");

                    b.Property<string>("JefeInmediato")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Marca")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("MesesADevengar")
                        .HasColumnType("int");

                    b.Property<decimal?>("MontoCongelado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NombreColaborador")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NombreCurso")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("NumeroRegistro")
                        .HasColumnType("int");

                    b.Property<string>("OrigenColaborador")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("RelacionLaboral")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Resultado")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("SolicitadoPor")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Tipo")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("ValorAsumidoEmpresa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.HasKey("Id");

                    b.HasIndex("CedulaColaborador")
                        .HasDatabaseName("IX_Convenio_Cedula");

                    b.HasIndex("ConvenioReferenciaId")
                        .HasDatabaseName("IX_Convenio_Referencia");

                    b.ToTable("Convenio", "dbo");
                });

            modelBuilder.Entity("Capacitaciones.Domain.Entities.ConvenioAnexo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContentType")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("ConvenioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("NombreAlmacenado")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NombreOriginal")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("TamanoBytes")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ConvenioId");

                    b.ToTable("ConvenioAnexo", "dbo");
                });

            modelBuilder.Entity("Capacitaciones.Domain.Entities.ConvenioItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ConvenioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Devengable")
                        .HasColumnType("bit");

                    b.Property<string>("Observacion")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ConvenioId");

                    b.ToTable("ConvenioItem", "dbo");
                });

            modelBuilder.Entity("Capacitaciones.Domain.Entities.ConvenioNumeracion", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("SiguienteNumero")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UltimaActualizacion")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ConvenioNumeracion", "dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            SiguienteNumero = 1
                        });
                });

            modelBuilder.Entity("Capacitaciones.Domain.Entities.Modalidad", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("UX_Modalidad_Nombre");

                    b.ToTable("Modalidad", "dbo");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111001"),
                            Activo = true,
                            FechaCreacion = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Presencial"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111002"),
                            Activo = true,
                            FechaCreacion = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Virtual"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111003"),
                            Activo = true,
                            FechaCreacion = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Híbrida"
                        });
                });

            modelBuilder.Entity("Capacitaciones.Domain.Entities.PreguntaEncuesta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("OpcionesJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("TipoActividadId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TipoPregunta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("TipoActividadId")
                        .HasDatabaseName("IX_PreguntaEncuesta_TipoActividadId");

                    b.ToTable("PreguntaEncuesta", "dbo");
                });

            modelBuilder.Entity("Capacitaciones.Domain.Entities.Recurso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("ContentType")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Extension")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("NombreAlmacenado")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NombreOriginal")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("TamanoBytes")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Activo")
                        .HasDatabaseName("IX_Recurso_Activo")
                        .HasFilter("[Activo] = 1");

                    b.HasIndex("NombreAlmacenado")
                        .IsUnique()
                        .HasDatabaseName("UX_Recurso_NombreAlmacenado");

                    b.ToTable("Recurso", "dbo");
                });

            modelBuilder.Entity("Capacitaciones.Domain.Entities.Responsable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)")
                        .HasDefaultValue("");

                    b.Property<string>("Empresa")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Firma")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Responsable", "dbo");
                });

            modelBuilder.Entity("Capacitaciones.Domain.Entities.RespuestaEncuesta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AsistenteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaRespuesta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<Guid>("PreguntaEncuestaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Respuesta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PreguntaEncuestaId");

                    b.HasIndex("AsistenteId", "PreguntaEncuestaId")
                        .IsUnique()
                        .HasDatabaseName("UX_RespuestaEncuesta_Asistente_Pregunta");

                    b.ToTable("RespuestaEncuesta", "dbo");
                });

            modelBuilder.Entity("Capacitaciones.Domain.Entities.TipoActividad", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("UX_TipoActividad_Nombre");

                    b.ToTable("TipoActividad", "dbo");

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222001"),
                            Activo = true,
                            FechaCreacion = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Charla"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222002"),
                            Activo = true,
                            FechaCreacion = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Workshop"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222003"),
                            Activo = true,
                            FechaCreacion = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Capacitación"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222004"),
                            Activo = true,
                            FechaCreacion = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Curso"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222005"),
                            Activo = true,
                            FechaCreacion = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Taller"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222006"),
                            Activo = true,
                            FechaCreacion = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Seminario"
                        });
                });

            modelBuilder.Entity("Capacitaciones.Domain.Entities.Asistente", b =>
                {
                    b.HasOne("Capacitaciones.Domain.Entities.Area", "Area")
                        .WithMany()
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Capacitaciones.Domain.Entities.Capacitacion", "Capacitacion")
                        .WithMany()
                        .HasForeignKey("CapacitacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("Capacitacion");
                });

            modelBuilder.Entity("Capacitaciones.Domain.Entities.Capacitacion", b =>
                {
                    b.HasOne("Capacitaciones.Domain.Entities.Modalidad", "Modalidad")
                        .WithMany()
                        .HasForeignKey("ModalidadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Capacitaciones.Domain.Entities.TipoActividad", "TipoActividad")
                        .WithMany()
                        .HasForeignKey("TipoActividadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Modalidad");

                    b.Navigation("TipoActividad");
                });

            modelBuilder.Entity("Capacitaciones.Domain.Entities.CapacitacionResponsable", b =>
                {
                    b.HasOne("Capacitaciones.Domain.Entities.Capacitacion", "Capacitacion")
                        .WithMany("CapacitacionResponsables")
                        .HasForeignKey("CapacitacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Capacitaciones.Domain.Entities.Responsable", "Responsable")
                        .WithMany()
                        .HasForeignKey("ResponsableId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Capacitacion");

                    b.Navigation("Responsable");
                });

            modelBuilder.Entity("Capacitaciones.Domain.Entities.Convenio", b =>
                {
                    b.HasOne("Capacitaciones.Domain.Entities.Convenio", "ConvenioReferencia")
                        .WithMany()
                        .HasForeignKey("ConvenioReferenciaId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("ConvenioReferencia");
                });

            modelBuilder.Entity("Capacitaciones.Domain.Entities.ConvenioAnexo", b =>
                {
                    b.HasOne("Capacitaciones.Domain.Entities.Convenio", null)
                        .WithMany("Anexos")
                        .HasForeignKey("ConvenioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Capacitaciones.Domain.Entities.ConvenioItem", b =>
                {
                    b.HasOne("Capacitaciones.Domain.Entities.Convenio", null)
                        .WithMany("Items")
                        .HasForeignKey("ConvenioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Capacitaciones.Domain.Entities.PreguntaEncuesta", b =>
                {
                    b.HasOne("Capacitaciones.Domain.Entities.TipoActividad", "TipoActividad")
                        .WithMany()
                        .HasForeignKey("TipoActividadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TipoActividad");
                });

            modelBuilder.Entity("Capacitaciones.Domain.Entities.RespuestaEncuesta", b =>
                {
                    b.HasOne("Capacitaciones.Domain.Entities.Asistente", "Asistente")
                        .WithMany()
                        .HasForeignKey("AsistenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Capacitaciones.Domain.Entities.PreguntaEncuesta", "PreguntaEncuesta")
                        .WithMany()
                        .HasForeignKey("PreguntaEncuestaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Asistente");

                    b.Navigation("PreguntaEncuesta");
                });

            modelBuilder.Entity("Capacitaciones.Domain.Entities.Capacitacion", b =>
                {
                    b.Navigation("CapacitacionResponsables");
                });

            modelBuilder.Entity("Capacitaciones.Domain.Entities.Convenio", b =>
                {
                    b.Navigation("Anexos");

                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
